#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
---
namespace: apps
DOCKER_REGISTRY: ''
env:
  # The INFLUXDB_USERNAME and INFLUXDB_PASSWORD length must be a minimum of 5 and 10 characters respectively and 
  # should contain alphanumeric characters with atleast one digit. 
  # Do not set INFLUXDB_USERNAME to 'admin'.
  # Do not use the following special characters in the influxdb_username and influxdb_password "~:'+[/@^{%(-"*|,&<`}._=}!>;?#$)\"
  INFLUXDB_USERNAME: 
  INFLUXDB_PASSWORD: 
  # The VISUALIZER_GRAFANA_USER and VISUALIZER_GRAFANA_PASSWORD length must be a minimum of 5 and 10 characters respectively 
  # and should contain alphanumeric characters with atleast one digit
  VISUALIZER_GRAFANA_USER: 
  VISUALIZER_GRAFANA_PASSWORD: 
  # The POSTGRES_USER length must be a minimum of 5 and 10 characters respectively
  POSTGRES_PASSWORD:
  # MinIO Secret Key length must be a minimum of 8 and 16 characters respectively and should contain alphanumeric characters with at least one digit 
  MINIO_SECRET_KEY:
  HTTP_PROXY: 
  HTTPS_PROXY: 