#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
name: "[Wind Turbine Sample App] PR workflow"
run-name: "[Wind Turbine Sample App] PR  workflow (by @${{ github.actor }} via ${{ github.event_name }})"
on:
  pull_request:
    paths:
      - 'manufacturing-ai-suite/wind-turbine-anomaly-detection/*'
  workflow_call:
  workflow_dispatch:
permissions: {}

jobs:
  windturbine-sample-app-pre-merge-build:
    permissions:
      contents: read
      packages: read          # needed for actions/checkout
    runs-on: ubuntu-24.04
    steps:
    - name: Runner workspace path
      run: |
        echo "Cleaning up previous run"
        if [ -n "$(docker ps -aq)" ]; then
            docker stop $(docker ps -aq)
        fi
        if [ -n "$(docker ps -aq)" ]; then
            docker rm $(docker ps -aq)
        fi
        docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi -f
    - name: Checkout edge-ai-libraries (main)
      uses: actions/checkout@v4
      with:
        repository: open-edge-platform/edge-ai-libraries
        ref: main
        path: edge-ai-libraries
    - name: Building Time Series Analytics microservices
      run: |
        cd ./edge-ai-libraries/microservices/time-series-analytics/docker
        docker compose down -v 
        docker compose build
    - uses: actions/checkout@v4
      with:
          path: timeseries
    - name: Building Wind Turbine Anomaly Detection Sample App
      run: |
        cd ./timeseries/manufacturing-ai-suite/wind-turbine-anomaly-detection
        make down 
        sed -i "s/INFLUXDB_ADMIN_USERNAME=.*/INFLUXDB_ADMIN_USERNAME=admin/g" .env
        sed -i "s/INFLUXDB_ADMIN_PASSWORD=.*/INFLUXDB_ADMIN_PASSWORD=admin123/g" .env
        sed -i "s/INFLUXDB_USERNAME=.*/INFLUXDB_USERNAME=user/g" .env
        sed -i "s/INFLUXDB_PASSWORD=.*/INFLUXDB_PASSWORD=user123/g" .env
        sed -i "s/VISUALIZER_GRAFANA_USER=.*/VISUALIZER_GRAFANA_USER=admin/g" .env
        sed -i "s/VISUALIZER_GRAFANA_PASSWORD=.*/VISUALIZER_GRAFANA_PASSWORD=admin123/g" .env
        sed -i "s/MR_PSQL_PASSWORD=.*/MR_PSQL_PASSWORD=admin123/g" .env
        sed -i "s/MR_MINIO_ACCESS_KEY=.*/MR_MINIO_ACCESS_KEY=user/g" .env
        sed -i "s/MR_MINIO_SECRET_KEY=.*/MR_MINIO_SECRET_KEY=admin12345/g" .env
        make build
    - name: Deploying Wind Turbine Anomaly Detection Sample App
      run: |
        cd "${{ github.workspace }}"
        cd ./timeseries/manufacturing-ai-suite/wind-turbine-anomaly-detection
        echo "Deploying Wind Turbine Anomaly Detection Sample App"
        echo "Deploying using mqtt ingestion"
        make up_mqtt_ingestion
        echo "Deploying using opcua ingestion"
        make up_opcua_ingestion
    - name: Undeploying Wind Turbine Anomaly Detection Sample App
      run: |
        cd "${{ github.workspace }}"
        cd ./timeseries/manufacturing-ai-suite/wind-turbine-anomaly-detection
        make down